### ISSUE TITLE
Dúvidas Sobre os requisitos do projeto.

### ISSUE THREAD

**Issue by gervasiodbjr** [AdailCarvalho/firewarning-api#1]
1. No método de cadastro do usuário descrito, não é cadastrada a senha. Adiciono parâmetro 'password' no método de criação de usuário, ou sete uma padrão para cada tipo (ADMIN, SISTEMA e POPULACAO)?

2. Caso o usuário tenha cadastrado uma empresa favorita, ela pode ser listada no método GET?

**Comment by AdailCarvalho** [comment]
Olá, @gervasiodbjr 

No tópico [2], é citado : 

> Para diferenciar usuários, é interessante que o sistema forneça API key's ou algum outro meio para identificar que o usuário do APP possui permissão de edições (PUT / POST / DELETE).

O servidor pode gerar uma chave de autenticação pra cada usuário que for diferente de _POPULAÇÃO_, ao cadastrá-lo. Para usuários do tipo _POPULAÇÃO_, ele cadastra  informações básicas (nome/ email), mas não precisa gerar chave.

A partir disso, quaisquer requisições que necessitem permissão, necessitarão informar a chave. Se a chave for válida para o usuário, e se usuário tem permissão para requisitar o respectivo método, prossegue. Caso contrário,  barra a requisição. 

Sobre a segunda pergunta, não há restrição pra listar de modo geral as empresas, bem como requisitar o status de uma específica. A única restrição de busca de informações via GET,  está especificada no item [4], onde o servidor deve fornecer uma maneira de buscar reports utilizando uma série de filtros.

Abraço.

**Comment by gervasiodbjr** [comment]
Estou finalizando o desafio.
Não consegui enviar antes porque estou tendo que implementar o desafio quando chego à noite, mas amanhã estarei enviando para o GitHub e para o email.




Cordialmente,

--------------------------------------------------
Gervásio D. Bandeira Jr.
Analista de Software e Eng. Eletrônico
CREA 44885 CE
Tel.: +55 85 99901-3748

gervasiodbjr@gmail.com
